#!/bin/bash

mkdir base/MacOS
mkdir App
mkdir App/qf
mkdir App/qf/Contents

cp bin/QuickFlash base/MacOS
chmod +x base/MacOS/QuickFlash

cp assets/1.png base/Resources
cp assets/ApplicationStub.icns base/Resources
cp assets/document.wflow base
cp assets/qf.py base/Resources

cp -R base/ App/qf/Contents
mv App/qf App/QuickFlash.app

app_file="App/QuickFlash.app"
dmg_file="App/QuickFlash-Beta-v0_5_.dmg"
alias_name="QuickFlash Beta"
sudo ln -s "/Applications" "App/"
sudo hdiutil create -volname "$alias_name" -fs HFS+ -srcfolder "App/" "$dmg_file"
wait
sudo hdiutil attach "$dmg_file"
wait
sudo hdiutil convert "$dmg_file" -format UDZO -o "App/QuickFlash-Beta-v0_5_0.dmg"
wait
sudo hdiutil detach "/Volumes/QuickFlash Beta"
sudo rm -rf "App/QuickFlash-Beta-v0_5_.dmg"

mkdir App_standalone/
cp -R App/QuickFlash.app App_Standalone/
wait
cp -R assets/PIL App_Standalone/QuickFlash.app/Contents/Resources/PIL
wait
cp -R assets/PyQt5 App_Standalone/QuickFlash.app/Contents/Resources/PyQt5
wait
cp -R assets/usb App_Standalone/QuickFlash.app/Contents/Resources/usb
wait
chmod +x App_Standalone/QuickFlash.app/Contents/MacOS/QuickFlash
sudo ln -s "/Applications" "App_Standalone/"
wait
dmg_file="App_Standalone/QuickFlash-Standalone-Beta-v0_5_.dmg"
sudo hdiutil create -volname "$alias_name" -fs HFS+ -srcfolder "App_Standalone/" "$dmg_file"
wait
sudo hdiutil attach "$dmg_file"
wait
sudo hdiutil convert "$dmg_file" -format UDZO -o "App_Standalone/QuickFlash-Beta-Standalone-v0_5_0.dmg"
wait
sudo hdiutil detach "/Volumes/QuickFlash Beta"
sudo rm -rf "App_Standalone/QuickFlash-Standalone-Beta-v0_5_.dmg"